# 4. Data Retrieval & Filtering

# Select all data: 
SELECT * FROM STUDENT;

# Select specific columns: 
SELECT RNO, NAME FROM STUDENT;

# Filter with WHERE clause: 
SELECT * FROM STUDENT WHERE PERCENTAGE > 60;
SELECT * FROM STUDENT WHERE PERCENTAGE = 60;
SELECT * FROM STUDENT WHERE PERCENTAGE = 60 OR PERCENTAGE = 80;
SELECT * FROM STUDENT WHERE PERCENTAGE BETWEEN 60 AND 80;
SELECT * FROM STUDENT WHERE PERCENTAGE != 60;


# 5. Data Modification

# Insert a record: 
INSERT INTO STUDENT VALUES (101, 'RAMA', '1234567892', 18, 'JODHPUR', 99.98);
INSERT INTO STUDENT (RNO, NAME) VALUES (102, 'JON');

# Update existing records:
UPDATE STUDENT SET PERCENTAGE = 100;
UPDATE STUDENT SET PERCENTAGE = 90 WHERE NAME = 'RAMA';

# Delete records:
DELETE FROM STUDENT WHERE RNO = 101;
DELETE FROM STUDENT;


# 6. Advanced Queries

# Select distinct values:
SELECT DISTINCT NAME FROM STUDENT;

# Using IN operator:
SELECT * FROM STUDENT WHERE PERCENTAGE IN (60, 70, 80, 90);

# Pattern matching with LIKE:
SELECT NAME FROM STUDENT WHERE NAME LIKE 'A%';
SELECT NAME FROM STUDENT WHERE NAME LIKE '%A';
SELECT NAME FROM STUDENT WHERE NAME LIKE '%A%';
SELECT NAME FROM STUDENT WHERE NAME LIKE '_A%';
SELECT NAME FROM STUDENT WHERE NAME LIKE 'A_';
SELECT NAME FROM STUDENT WHERE NAME LIKE '_____';
SELECT NAME FROM STUDENT WHERE NAME LIKE 'A%O';